(netlist-dsl
  (let (
    (ENT4 (:other "big-electric-pole"))
    (ENT5 (:cond :signal-pink 0 :> :signal-everything t))
    (ENT6 (:cond :signal-0 72 := :signal-pink nil))
    (ENT7 (:other "big-electric-pole"))
    (ENT8 (:other "big-electric-pole")))
  (:conn-inputs ENT4 ENT6 :green)
  (:conn ENT7 ENT5 :green)
  (:conn ENT6 ENT5 :red)
  (:conn-outputs ENT5 ENT8 :red)
  (:conn ENT4 ENT6 :green)
  (:conn ENT6 ENT5 :red)
  (:conn-inputs ENT7 ENT5 :green)
  (:conn ENT5 ENT8 :red)
  (list ENT8 ENT4 ENT5 ENT6 ENT7)))
